{{ $metricsPort := include "validate.metricsPort" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-local-storage-exporter-service
  labels:
    app: {{ .Release.Name }}-local-storage-exporter
spec:
  selector:
    app: {{ .Release.Name }}-local-storage-exporter
  ports:
    - protocol: TCP
      name: metrics
      port: {{ $metricsPort }}
      targetPort: metrics